#%RAML 1.0 NamedExample
trip:
  description: This is first trip
  startDate: 2019-12-15
  returnDate: 2019-12-25
  destinationAddress: 1234 Main St, ExcellentCity, oh
  destinationDetails: Awesome Place
  hotelReservation: Done
  rentalCar: Done 
  estimatedExpense: 2000
  